language: android
sudo: required
dist: trusty
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
cache:
  directories:
    - $HOME/.gradle/caches/2.11
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

env:
  global:
   - secure: "YT/7/BbtCbOhHpiDCFKsBYl49u7d/+wDCZdkj1QUl+4u54u+2b/p5oX9ASoK8taYrUijE84mdJhBlLrX9Rplo12jQOlCkKdrW4oaDhUq2Mio63hNGIx4JSe+ycuIeDCWNK+JQ2qUnNWdagFlLPM+3KJZKudewkAlfZp+BQAmFA735UmbVoNSTKV2KToitb0H6NbCzu6ZRyfz0ncqM1ZgidJ+9vI5S18Y+l2EPnaLmIuiK34P0Q2hwULdrCsPvkstFWRdukqu3kTSv3ATtlqU/kOzeWiXmqySIG5sZX1EHTW871n3+WF8IF+5D5ocQzzkUI3KpreQWwwO8pfP0v1aiyhi4GfGHgHj1ZGa6JfD3W/uQCUOD9ovow/tkhgdt1DIoPEi4z3Ct0o6JQUC7npDCcRPj/dJAHQ0JT0uo1UcIjq63pibIrW1fT6Bd+iZITR8d18wAOwWOaBhsgHscQ0YVfxqaK/XX13gFwvdxt4TsAnWpWWW3ugG7QsbDya+PO4jfWbSDFDVnDYzbIsABOvJ6CtQhlt3bmbDzii4BAjF82QpDQ+T0xIIMlf5c6TbzyQOrt1Pw1SpK3L5iWit2fZwVUrIuBMP73CbK6F52Hxa763iQqdqWPFRGjsPBwgJOsdkUc/mXD9pbwGEEGSvAvOesJd5ctgmwXWlAkoBKUNew7w="

addons:
  coverity_scan:
    project:
      name: "aaronjwood/PortAuthority"
    notification_email: aaronjwood@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master
