language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.11
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
